In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("CSV/Luxury_Housing_Bangalore.csv")

In [3]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [ ]:
df.describe() #summary stat

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [6]:
df.isnull()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [8]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
100995     True
100996     True
100997     True
100998     True
100999     True
Length: 101000, dtype: bool

In [9]:
df.duplicated().sum()

np.int64(1000)

In [10]:
df.drop_duplicates(inplace= True)

In [11]:
df.sample(15)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
19332,PROP019333,Bannerghatta Road,Project_332,Godrej,8335.0,4Bhk,₹16.37 Cr,Primary,Startup Founder,2023-09-30,4.212826,8.057219,Ready to move,NRI Desk,yes,7.766032,48,Too far from my office.
52640,PROP052641,sarjapur road,Project_140,Godrej,5036.0,3BHK,8.131860145517182,Primary,NRI,2023-06-30,5.181281,6.327693,Launch,Direct,no,9.176056,109,NaN
29178,PROP029179,domlur,Project_178,Prestige,4915.0,5bhk+,₹13.45 Cr,Secondary,Startup Founder,2024-09-30,9.074062,6.078749,Ready to move,NRI Desk,no,7.875321,21,Underpriced for location.
40407,PROP040408,Sarjapur Road,Project_407,Tata Housing,5459.0,3BHK,11.465772834659756,Secondary,Startup Founder,2024-06-30,5.496132,7.034593,Launch,Online,yes,9.463700,22,Loved the amenities!
88984,PROP088985,Bannerghatta Road,Project_484,Godrej,5498.0,4Bhk,12.270070533674708,Primary,HNI,2023-09-30,6.116415,5.527841,Launch,NRI Desk,yes,8.548661,45,Underpriced for location.
32583,PROP032584,bellary road,Project_83,Sobha,6955.0,5bhk+,14.229391288169966,Secondary,Other,2024-06-30,6.372882,8.412034,Under construction,Online,no,6.480581,60,Will buy after possession.
76130,PROP076131,domlur,Project_130,Tata Housing,6821.0,4Bhk,13.983625117688502,Primary,CXO,2024-09-30,9.885448,5.409921,Ready to move,Direct,yes,6.283658,108,Great value for money.
44102,PROP044103,kanakapura road,Project_102,L&T Realty,8013.0,4Bhk,₹15.85 Cr,Secondary,Other,2023-09-30,9.558805,6.126950,Launch,Online,yes,6.938121,66,Great view from 15th floor.
72484,PROP072485,Jayanagar,Project_484,SNN Raj,4548.0,5BHK+,16.71556657739298,Secondary,CXO,2024-03-31,6.986184,5.547963,Ready to move,NRI Desk,yes,8.201197,28,Great value for money.
62650,PROP062651,Mg Road,Project_150,Brigade,5407.0,3bhk,9.910731182204021,Secondary,HNI,2024-03-31,7.709268,9.843389,Launch,NRI Desk,yes,5.523074,75,Agent was not responsive.
71320,PROP071321,SARJAPUR ROAD,Project_320,L&T Realty,3152.0,3Bhk,10.246966913690267,Secondary,NRI,2025-03-31,6.091186,9.149779,Under construction,NRI Desk,yes,6.445495,23,NaN
1153,PROP001154,jp nagar,Project_153,Puravankara,5370.0,3BHK,15.787043976655085,Secondary,CXO,2025-03-31,7.724953,5.772651,Ready to move,Direct,yes,7.038740,69,NaN
10639,PROP010640,Bellary Road,Project_139,Embassy,8161.0,4BHK,₹12.32 Cr,Secondary,Other,2024-03-31,4.984326,5.672927,Launch,Direct,no,7.249265,56,Great value for money.
44072,PROP044073,Bellary Road,Project_72,Godrej,3032.0,5BHK+,16.4887839994226,Primary,HNI,2024-12-31,4.110132,6.335047,Under construction,Direct,yes,5.956502,46,Connectivity is poor.
10202,PROP010203,Domlur,Project_202,Puravankara,4841.0,4BHK,12.889698546978908,Secondary,CXO,2024-03-31,6.855298,5.320156,Ready to move,Online,yes,6.212878,115,Will buy after possession.

In [12]:
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].astype(str).str.replace('Cr', '', regex=False).str.strip().str.replace('Rs','').str.replace('₹','')
df['Ticket_Price_Cr'] = pd.to_numeric(df['Ticket_Price_Cr'], errors='coerce')

In [13]:
df['Ticket_Price_Cr']

0        12.750846
1        16.292152
2        10.517724
3         9.396367
4        15.345392
           ...
99995    10.185193
99996    12.272081
99997    13.730179
99998    10.363989
99999    10.415617
Name: Ticket_Price_Cr, Length: 100000, dtype: float64

In [14]:
df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].fillna(df['Unit_Size_Sqft'].mean())
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].mean())
df['Amenity_Score'] = df['Amenity_Score'].fillna(df['Amenity_Score'].median())
df['Buyer_Comments'] = df['Buyer_Comments'].fillna("No Comments")

In [15]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under construction,NRI Desk,no,7.723898,106,No Comments
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,8.379908,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,PROP099997,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,PROP099998,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,No Comments
99998,PROP099999,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Comments
99999,PROP100000,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,No Comments

In [16]:
df.dtypes

Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr         float64
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [17]:
text_cols = ['Micro_Market', 'Developer_Name', 'Configuration',
             'Transaction_Type', 'Buyer_Type', 'Possession_Status',
             'Sales_Channel', 'NRI_Buyer']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [18]:
df["Price_per_Sqft"] = df["Ticket_Price_Cr"] * 10000000 / df["Unit_Size_Sqft"]

In [19]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4Bhk,12.750846,Primary,Nri,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.120594
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under Construction,Nri Desk,No,7.723898,106,No Comments,28284.985887
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4Bhk,10.517724,Primary,Hni,2023-12-31,8.131315,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.976013
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3Bhk,9.396367,Primary,Hni,2024-03-31,7.501657,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!,15175.012103
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,Hni,2024-12-31,4.525216,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.,21471.096187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,Nri,2023-12-31,8.379908,7.499766,Under Construction,Online,Yes,8.378800,109,Underpriced for location.,18351.699990
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,Yes,7.025209,20,Great view from 15th floor.,38700.980123
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4Bhk,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,Nri Desk,Yes,8.984990,63,No Comments,24522.555158
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4Bhk,10.363989,Primary,Nri,2024-09-30,9.435646,6.369276,Under Construction,Nri Desk,Yes,7.634717,89,No Comments,14116.029667
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,Yes,6.039943,95,No Comments,20764.786348

In [20]:
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])
df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter
df['Quarter_Number']

0        1
1        2
2        4
3        1
4        4
        ..
99995    4
99996    4
99997    3
99998    3
99999    3
Name: Quarter_Number, Length: 100000, dtype: int32

In [21]:
print(df['Purchase_Quarter'].unique())

<DatetimeArray>
['2025-03-31 00:00:00', '2024-06-30 00:00:00', '2023-12-31 00:00:00',
 '2024-03-31 00:00:00', '2024-12-31 00:00:00', '2023-09-30 00:00:00',
 '2024-09-30 00:00:00', '2023-06-30 00:00:00']
Length: 8, dtype: datetime64[ns]

In [22]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4Bhk,12.750846,Primary,Nri,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.120594,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under Construction,Nri Desk,No,7.723898,106,No Comments,28284.985887,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4Bhk,10.517724,Primary,Hni,2023-12-31,8.131315,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.976013,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3Bhk,9.396367,Primary,Hni,2024-03-31,7.501657,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!,15175.012103,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,Hni,2024-12-31,4.525216,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.,21471.096187,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,Nri,2023-12-31,8.379908,7.499766,Under Construction,Online,Yes,8.378800,109,Underpriced for location.,18351.699990,4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,Yes,7.025209,20,Great view from 15th floor.,38700.980123,4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4Bhk,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,Nri Desk,Yes,8.984990,63,No Comments,24522.555158,3
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4Bhk,10.363989,Primary,Nri,2024-09-30,9.435646,6.369276,Under Construction,Nri Desk,Yes,7.634717,89,No Comments,14116.029667,3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,Yes,6.039943,95,No Comments,20764.786348,3

In [23]:
df['Transaction_Type'].unique()

array(['Primary', 'Secondary'], dtype=object)

In [24]:
# Create Booking_count from Transaction_Type
# Let's assume Primary = booked (1), Secondary = not booked (0)
df['Booking_count'] = df['Transaction_Type'].str.lower().map({'primary': 1, 'secondary': 0})

In [25]:
df.rename(columns={"Developer_Name": "Builder"}, inplace=True)

In [28]:
!pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in f:\phone pe pro\venv\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in f:\phone pe pro\venv\lib\site-packages (from SQLAlchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in f:\phone pe pro\venv\lib\site-packages (from SQLAlchemy) (4.14.1)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import sys
!{sys.executable} -m pip install SQLAlchemy

'f:\phone' is not recognized as an internal or external command,
operable program or batch file.

In [30]:
from sqlalchemy import create_engine

# Create engine
engine = create_engine("mysql+pymysql://root:Yogapriya1234@localhost:3306/lux_db")

In [31]:
"""df.to_sql("luxury_housing", engine, if_exists="replace", index=False)"""

'df.to_sql("luxury_housing", engine, if_exists="replace", index=False)'